export const API_TYPE = 'https://pokeapi.co/api/v2/type/'
export const API_ALLPOKEMONS = 'https://pokeapi.co/api/v2/pokemon?limit=20'
export const API_GETPOKEMON = 'https://pokeapi.co/api/v2/pokemon'
export const API_GETEVOLUTIONS = 'https://pokeapi.co/api/v2/evolution-chain'
export const API_GETSPECIES = 'https://pokeapi.co/api/v2/pokemon-species'
